### ISSUE TITLE
error colorizing python code

### ISSUE THREAD

**Issue by rubo77** [garabik/grc#11]
grcat $(which grc)

results in:

    Traceback (most recent call last):
      File "/usr/bin/grcat", line 98, in <module>
        keyword, value = split(l[:-1], "=", 1)
    ValueError: need more than 1 value to unpack

**Comment by richarson** [comment]
That's not hou you use grcat, per the README:
```
grcat conf.log < $(which grc)
```

Of course, there's no conf.python so the coloring will be less than ideal :)

**Comment by garabik** [comment]
@richarson Indeed, thanks for explaining. I've added slightly more informative error message.

**Comment by garabik** [comment]
@richarson Indeed, thanks for explaining. I've added slightly more informative error message.

**Comment by rubo77** [comment]
if its this commit: https://github.com/garabik/grc/commit/0ae0ce08a8412c7fe3660aea949d8df73c9a3b9 , I'd suggest to add a hint when you call it like I did intuitively in my first post here, that you have to call `grc` with the option `conf.log` and redirect the file into grc with `<`

**Comment by garabik** [comment]
@rubo77 I admit it was a bad "design decision", `grcat` should have probably used a switch to select the configuration file. I am thinking about reworking the logic a bit.

**Comment by rubo77** [comment]
https://github.com/garabik/grc/issues/23
