### ISSUE TITLE
`ls -lah` not colorized properly when listing a specific path

### ISSUE THREAD

**Issue by nicholas-ochoa** [garabik/grc#159]
I noticed when I'm in a directory such as `/var/log/` and I run `ls -lah` I get the expected output (colorized), but when running `ls -lah /var/log` the colorization doesn't appear complete. The output is the same however:

`ls -lah`
![2020-07-28 12_19_08-Window](https://user-images.githubusercontent.com/126299/88699446-f6c17200-d0cc-11ea-8c6f-067730dabebc.png)

`ls -lah /var/log`
![2020-07-28 12_19_40-Window](https://user-images.githubusercontent.com/126299/88699463-fcb75300-d0cc-11ea-89ba-0ca05a8b920a.png)

Using the latest commit from the devel branch. Using master / release version and there are no colors at all in the `ls -lah /var/log` example.

**Comment by init-01** [comment]
Comment lines
```
# log file
\b\w+\b.*log\b
conf.log
```
in `/etc/grc.conf`

Regular expression `\b\w+\b.*log` recognized `/var/log` part as log file

**Comment by garabik** [comment]
Fixed in 7cd8fff5e1862fa8e886dedec8a1a2dfc8bbeacc
