### ISSUE TITLE
Trying to grc tail -fv piping to grep removes color, Anyone with Strong Kungfu?

### ISSUE THREAD

**Issue by Jieiku** [garabik/grc#195]
This works perfectly:

`grc tail -fv /var/log/asterisk/full`

I wanted to skip some results from the tail output, this works but removes color:

`grc tail -fv /var/log/asterisk/full | grep --color=always -Fvf /root/skip.txt`

as you can see i tried --color=always but it did not help... I dont need to use grep if somebody knows another way to omit patterns from the output of `tail -f` while preserving the grc color.

**Comment by rouba002** [comment]
Just reverse the order of the commands?
tail -fv /var/log/asterisk/full | grep -Fvf /root/skip.txt | grcat <ASTERISK_FORMATER_CONFIG>

**Comment by Jieiku** [comment]
THANKS! That seems to work! I really appreciate it.

`tail -fv /var/log/asterisk/full | grep -Fvf /root/skip.txt | grcat /usr/share/grc/conf.log`
