### ISSUE TITLE
using grc with javac produces error

### ISSUE THREAD

**Issue by sxrayn** [garabik/grc#22]
**/etc/grc.conf**
```
# javac
(^|[/\w\.]+/)javac\s?
conf.javac
```
**/usr/share/grc/conf.javac**
```
# warning
regexp=warning
colour=yellow
=======
# error
regexp=error
colour=red
=======
```
**Result**
```
[ra@archnb AESKeyLock]$ grc javac
Traceback (most recent call last):
  File "/usr/bin/grcat", line 152, in <module>
    ll['regexp'] = re.compile(ll['regexp']).search
KeyError: 'regexp'
Usage: javac <options> <source files>
...
```

I'm not completely sure this isn't some kind of user error, but I don't know how to fix it myself?

**Comment by iax7** [comment]
Try changing your **/usr/share/grc/conf.javac** file to
```
# warning
regexp=warning
colours=yellow
=======
# error
regexp=error
colours=red
=======
```

**Comment by sxrayn** [comment]
That did not work aswell.
This happens only on my notebook running javac 1.8.0_72 64bit on Arch 4.3.3-3
When I tried to reproduce the error in VM running Arch 4.3.3-2 and javac 1.8.0_66 no error appeared but it still didn't color the output.

**Comment by garabik** [comment]
`javac` in itself writes help message to the error output, not stdout, you have to use the -e switch to redirect stderr as well:

    grc -e javac

**Comment by sxrayn** [comment]
That still produces the error on my notebook. I'll try it in the VM later.
```
[ra@archnb AESKeyLock]$ grc -e javac Main.java #this file should produce javac errors
Traceback (most recent call last):
  File "/usr/bin/grcat", line 152, in <module>
    ll['regexp'] = re.compile(ll['regexp']).search
KeyError: 'regexp'
[ra@archnb AESKeyLock]$ 
```
Note that the javac output is no longer printed with -e.

**Comment by garabik** [comment]
Yes, a different error - remove the last line of `conf.javac` (the one with equal signs). It's trying to find regexp in the (empty) block below the line.

**Comment by sxrayn** [comment]
Okay, that fixed it.
Thanks for your time and sorry for the inconvenience caused.

**Comment by garabik** [comment]
Anyway, thanks for pointing this out - since it is somewhat that could be (and should have been) detected during conffile parsing.

I've just pushed a new version, block without regexps are silently ignored (perhaps later I'll add warning in such a case).
