### ISSUE TITLE
How can I install grc on Mac OS?

### ISSUE THREAD

**Issue by Paebbels** [garabik/grc#33]
Hello,

is there any package for Max OS?
At best in version 1.9 ;)

I have found packages for e.g. Debian, but not for Mac OS. I would like to provide an installation guide for Mac OS users, so they can experience the same features as Linux users.

**Update:**
I found a [brew formula](http://brewformulas.org/Grc) for Grc, but it has no version info or other description. There is only a link to the grc website. Can it be updated?

Related pull requests: #32 

**Update 2:**
According to an answer to issue #32, brew will install version 1.9.

Thanks
    Patrick

**Comment by lifeforms** [comment]
@Paebbels [MacPorts](https://www.macports.org) has a grc port!

```
# port info grc
grc @1.9 (textproc)

Description:          Generic Colouriser provides colourised output of logfiles and commands. It provides the grc and grcat Python
                      scripts for filtering text output and colourising it.
Homepage:             http://kassiopeia.juls.savba.sk/~garabik/software/grc.html

Library Dependencies: python27
Platforms:            darwin
License:              GPL-2
Maintainers:          nomaintainer@macports.org
```

**Comment by Paebbels** [comment]
Installing Xcode plus MacPorts, seams to be a very heavy way for such a little tool.... especially, when it's a Python tool, which could easily be delivered with pip.

For reference: [PyPI entry for 1.0b4](https://pypi.python.org/pypi/grc/1.0b4)

**Comment by derimagia** [comment]
See https://github.com/Homebrew/homebrew-core/blob/master/Formula/grc.rb (brew show "program" will give you info on it) - if I remember right I added --head to this a while back to get the dev version but 1.9 has been the last release apparently.
