### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by karlek** [garabik/grc#42]
I love using grc, makes my day a little brighter, but I noticed the last release were almost a year (or 27 commits) ago. Many new features have been added:

* Colorization of `df` header line.
* IPv6 support for `ifconfig`
* `docker` support: `ps`, `info`, `images`, `docker-machine`.
* `journalctl` support

Time for a new release? :)

**Comment by sarnobat** [comment]
I don't know where else to say this so I'll just say here, I love grcat too.

**Comment by karlek** [comment]
There's finally been a new release: https://github.com/garabik/grc/releases/tag/v1.10

Closing this issue.
