### ISSUE TITLE
grcat colourize stderr?

### ISSUE THREAD

**Issue by sarnobat** [garabik/grc#49]
Does `grcat` support colourizing stderr? If not, can it be added (possibly with the ability to specify a different conf file)?

I know `grc` has the `--stderr` option to (presumably) colourize stderr but I like to use `grcat` since it works nicely with pipes and thus is more Unix-philosophy-friendly than `grc`.

My redirection efforts so far have been unsuccessful:

`(>&2 echo "INFO error") | grcat ~/conf.tail 2>(grcat ~/conf.tail)`

**Comment by garabik** [comment]
Well, grcat is only a pipe, so you must feed it stderr. Something like this might work:

    (>&2 echo "INFO error") 2>&1 >/dev/null | grcat ~/gconf.tail

(note that you have to put stdout *somewhere* unless you want to mix it with stderr).

Incidentally, `grcat` is not designed well for standalone usage - with hindsight, I would model it more along the `cat` command - i.e. `$1` would be a filename to colorize etc.

**Comment by sarnobat** [comment]
Thanks for the info and feedback. It might take a while before I have time to try this out so for now I'm closing the ticket and will reopen it later if I have followup questions.
