### ISSUE TITLE
Error in ls command alias in osX

### ISSUE THREAD

**Issue by janrito** [garabik/grc#50]
The ls command is being aliased in `grc.bashrc` using:
```
alias ls='colourify ls --color'
```
Which results in: 

```
$ ls
ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]
```

`ls` in osx does not accept the `--color` option. In fact, I don't think it accepts any double minus options. The correct options is `-G` <https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/ls.1.html>

**Comment by nbalonso** [comment]
I am seeing the same thing.

Until this is solved a simple work around is to modify _grc_'s aliases

```bash
$ sed -i .bak 's/ls --color/ls -G/' /usr/local/etc/grc.bashrc && rm /usr/local/etc/grc.bashrc.bak
```

**Comment by garabik** [comment]
I removed the `--color` switch in ddc789bfc072030a41ab34ecf34d615843f39c35, apparently OSX `ls` and GNU `ls` are too different.
