### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory" in version 1.10_1

### ISSUE THREAD

**Issue by slhck** [garabik/grc#51]
I just installed the latest version from Homebrew, then sourced `"$(brew --prefix)/etc/grc.bashrc"`. I'm using zsh 5.3.1  When I run `ls` (or anything else that grc would colorize), I get this:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/grc/1.10_1/libexec/bin/grc", line 191, in <module>
    os.execvp(args[0], args)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 604, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 594, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
```

All my Homebrew logs are here: https://gist.github.com/slhck/bd7416f37c61745c1c787c209d0c1e52

Running `grc` itself works (although the `")` after `Options:` seems weird…):

```
Generic Colouriser 1.10
grc [options] command [args]
Options:")
-e --stderr    redirect stderr. If this option is selected,
               do not automatically redirect stdout
-s --stdout    redirect stdout, even if -e is selected
-c name --config=name    use name as configuration file for grcat
--colour=word  word is one of: on, off, auto
--pty          run command in pseudoterminal (experimental)
```

I can also disable grc by not sourcing the `.bashrc` file and then run it manually without problems:

```
$ grc -es --colour=auto ls
foo
bar
```

Any pointers?

**Comment by slhck** [comment]
I should add that this is not (yet) related to #9619, since it seems to fail before that.

**Comment by garabik** [comment]
Could you show me your `.bashrc` ? `grc.bashrc` as provided by the package was not meant to be compatible with `zsh` (but it was easy to make it compatible, you can try commit 18c968370859e54c20f2407d7b0f81d6c16d4c51 ).

**Comment by slhck** [comment]
That actually fixes it, thanks!

I've actually never had problems with zsh until now, so I didn't assume it could cause an issue now.

**Comment by caseyw** [comment]
I had the exact same issue, and the commit saved me. Thanks!

**Comment by miguno** [comment]
For other readers, I ran into the following error message:

```
grc: is: No such file or directory
```

It happened after I switched from bash to zsh.

Environment:
- macOS Mojave 10.14.5
- zsh (5.7.1) + oh-my-zsh + powerlevel9k

I had the following custom grc config file:

```shell
# ~/.grc/grc.bashrc
GRC="$(type -p grc)"
if [ "$TERM" != dumb ] && [ -n "$GRC" ]; then
    alias colourify="$GRC -es --colour=auto"
    alias blkid='colourify blkid'
  ...
fi
```
which was `source`'d in my ZSH config:

```shell
source "$HOME/.grc/grc.bashrc"
```

The fix was the one mentioned in https://github.com/garabik/grc/issues/51#issuecomment-278892617 (commit https://github.com/garabik/grc/commit/18c968370859e54c20f2407d7b0f81d6c16d4c51), i.e. I had to replace the line

```shell
GRC="$(type -p grc)"
```
with
```shell
GRC="$(which grc)"
```
