### ISSUE TITLE
non capturing group

### ISSUE THREAD

**Issue by theguly** [garabik/grc#7]
quite sure i'm overlooking some piece of readme and example, but i cant find how to color just a part of regexp match.
for example, i have a line like:

foo:pub;let's have a drink at the pub

and i want to have just the first "pub" coloured.

i'd do:
regexp=(?:\:)(\w+)(?:\;)
color=green

but no green string on my terminal.
did i get this wrong?

**Comment by garabik** [comment]
This should fail (and write a stacktrace on the terminal), because the keyword is `colours`, not `color`:

    regexp=(?::)(\w+)(?:\;)
    colours=green

Though you probably want:

    regexp=(?::)(\w+)(?:\;)
    colours=default, green

or simply:

    regexp=pub
    colors=green
    count=once

**Comment by theguly** [comment]
```regexp=(?::)(\w+)(?:\;)
colours=default, green```
works, thanks.
didn't use
```regexp=pub
count=once```
because the word pub is not fixed and could be different, but your second example do what i need.

thanks a lot
