### ISSUE TITLE
missing newline at end of configuration breaks last colour

### ISSUE THREAD

**Issue by Habbie** [garabik/grc#74]
grc 1.11.1, installed via macOS homebrew.

I copied conf.tcpdump and added this to it:
```
-
# DNS queries
regexp=((A|AAAA)\? [^ ]+)
colours=green
```

This works, but only if there is a newline after `green`. When I remove the newline, this happens:
```
Traceback (most recent call last):
  File "/usr/local/bin/grcat", line 166, in <module>
    [''.join([get_colour(x) for x in split(colgroup)]) for colgroup in split(ll['colours'], ',')]
  File "/usr/local/bin/grcat", line 166, in <listcomp>
    [''.join([get_colour(x) for x in split(colgroup)]) for colgroup in split(ll['colours'], ',')]
  File "/usr/local/bin/grcat", line 166, in <listcomp>
    [''.join([get_colour(x) for x in split(colgroup)]) for colgroup in split(ll['colours'], ',')]
  File "/usr/local/bin/grcat", line 84, in get_colour
    raise ValueError('Bad colour specified: '+x)
ValueError: Bad colour specified: gree
```

The error appears to be on line 138 of grcat, which assumes there is always a trailing character to remove:
```
        fields = split(l[:-1], "=", 1)
```

Changing that line to
```
        fields = split(l.strip(), "=", 1)
```

makes it work for me, but I'm unsure if stripping is always legal while parsing grc configs.

**Comment by garabik** [comment]
Thanks for the catch; using .strip() would disable using whitespaces at the end of regular expressions (which is not nice, because it is not really visible if you edit the files), so at the end I used .rstrip('\r\n')
