### ISSUE TITLE
zsh ls -l colours permissions instead of files

### ISSUE THREAD

**Issue by simonhaenisch** [garabik/grc#76]
![image](https://user-images.githubusercontent.com/3410759/30959644-55ab3e7c-a49d-11e7-98a7-a431c71c84be.png)

I want the file names to be colorized rather than the file permissions (or both), i. e.:

![image](https://user-images.githubusercontent.com/3410759/30959684-695c12fc-a49d-11e7-95a0-11b45524f3f6.png)

`grc` also kind of messes up `ls -F`:

![image](https://user-images.githubusercontent.com/3410759/30960738-67c954ec-a4a0-11e7-9b6b-8857a3c14e6b.png)

At the moment I'm just reseting `alias ls='/bin/ls'` after adding the `grc` aliases, but i don't get why `grc` would apply that kind of coloring? Or is there something wrong with my zsh config? (I use `CLICOLOR=true`)

**Comment by urxvtcd** [comment]
I experience the same issue with fish shell.

**Comment by urxvtcd** [comment]
I experience the same issue with fish shell.

**Comment by urxvtcd** [comment]
In fish it's probably because ls and ll are functions provided by default. Adding this to fish.config solves the problem:

```
function ls --description 'alias ll /bin/ls -las --color'
	grc /bin/ls --color $argv
end

function ll --description 'alias ll /bin/ls -las --color'
	grc /bin/ls -las --color $argv
end
```

**Comment by rholak** [comment]
I am seeing the same thing with `ls -F`. grc is inserting newlines after each directory entry vs. wrapping them like `ls` does by default:
![2017-11-29_102154](https://user-images.githubusercontent.com/423088/33385855-3dc91392-d4ef-11e7-9bce-f73954357c10.png)

**Comment by rholak** [comment]
I found a solution for the `ls -F` issue - if you add the `-C` option to force `ls` to output to columns, it will display correctly when going through grc:

![2017-11-29_103657](https://user-images.githubusercontent.com/423088/33386725-41f87352-d4f1-11e7-8efb-e62ce65a9d82.png)

I added the `-C` option to my `ls` alias for grc, and it works nicely for me now.

**Comment by nathan-gilbert** [comment]
Is there a way to colorize both the permissions and files in the fish shell in macOS?

I've tried:
`function ls --description 'alias ls'
    grc /bin/ls -G $argv
end`

but it doesn't work. Only the permissions are colored but not the files.

**Comment by HarukaMa** [comment]
It seems the original issue is never addressed. Why is this issue closed?

**Comment by simonhaenisch** [comment]
Because `alias ls='/bin/ls'` is a sufficient workaround for me 🤷🏻‍♂️

**Comment by HarukaMa** [comment]
I’ve edited `ls` out from the config file personally, but I would still like to see a proper solution to this issue...

iPhoneから送信

**Comment by fle108** [comment]
with ohmyzsh and grc plugin activated , using `alias ll="grc /bin/ls -alsh --color"` and `alias ls="grc /bin/ls --color"` as alias in .zshrc did the job for me
