### ISSUE TITLE
findmnt in grc.conf

### ISSUE THREAD

**Issue by Raizo62** [garabik/grc#77]
Hi

I believe that the configuration of findmnt is twice in "/etc/grc.conf"
first : line 65 : 
```
65 # findmnt command 
66 (^|[/\w\.]+/)findmnt\s? 
67 conf.findmnt 
```
second : line 164
```
164 # findmnt 
165 (^|[/\w\.]+/)findmnt\s? 
166 conf.findmnt 
```

I think that is not useful

**Comment by garabik** [comment]
Thanks, fixed in 375b6c3443a52bc74de97ab26c55b12ab99d8423
