### ISSUE TITLE
grc.zsh overrwrites existing aliases

### ISSUE THREAD

**Issue by bradparks** [garabik/grc#83]
Trying to use grc.zsh to integrate with zsh, it overwrites any existing aliases for the commands being colorized.

e.g. if I had

`alias ls='ls -ltr'`

set already, then sourcing `grc.zsh` overwrites my `ls` alias.
I think most people would put the colorizing at the end of their `.zshrc`, so this could be avoided by setting the alias to the value of an existing alias, if one exists.

The line that does it is here:
https://github.com/garabik/grc/blob/master/grc.zsh#L34

```      alias $cmd="grc --colour=auto $cmd"```

If you could pass in the current value of the alias if one exists, it'd avoid this issue.

**Comment by kapsh** [comment]
`whence` in zsh will do the trick. But I can't see a clear way to do this in bash since `which`, `type` and `command` will give unpredictable results which require ugly parsing of human-targeted output.
```bash

# Here we need just strip '$cmd is', right?
% type -p ls                                                                                                 
ls is /usr/host/bin/ls 
% type -p bash                                                                                               
bash is /usr/host/bin/bash

# No, it also could be 'an alias' too.
% type -a ls                                                                                                 
ls is an alias for ls --color=tty
ls is /usr/host/bin/ls
ls is /usr/host/bin/ls

# Maybe this would be simpler?
% command -v bash                                                                                            
/usr/host/bin/bash

# Nope.
% command -v ls                                                                                              
alias ls='ls --color=tty'
```

**Comment by bradparks** [comment]
nice you found a way to fix it for `zsh`, which I use ;-) But I see what you mean about bash aliases.... if I find a way, I'll let you know... Thanks!

**Comment by kapsh** [comment]
@bradparks Personally I don't care much about bash or fish (heavy zsh user too), but you can bring a patch or at least drop your ideas here and maybe then somedoby will implement it.

**Comment by richarson** [comment]
How about alias (similar to `command -v`, I guess):
```
$ alias ls
alias ls='ls -A --color=auto'

$ alias ls | cut -d '=' -f 2-
'ls -A --color=auto'
```

**Comment by richarson** [comment]
Nah, couldn't make it work :/

**Comment by richarson** [comment]
Second try, but if the original alias has escaped apostrophes (') this'll just strip them, so room for improvement :) :

```
$ alias ls
alias ls='ls -A --color=auto'

$ cmd=ls

$ alias ls | cut -d '=' -f 2- | tr -d "'"
ls -A --color=auto

$ alias=$(alias ls | cut -d '=' -f 2- | tr -d "'")

$ echo $alias
ls -A --color=auto

$ alias $cmd="grc --colour=auto $alias"

$ alias ls
alias ls='grc --colour=auto ls -A --color=auto'
```

**Comment by xPMo** [comment]
Here's another issue:
```bash
$ unalias ls
$ function ls { /usr/bin/ls -Alh "$@"; } # requires path to prevent recursion
$ which ls
/usr/bin/ls
$ command -v ls
ls
$ type ls
ls is a function
ls () 
{ 
    /usr/bin/ls -lAh "$@"
}
```
