### ISSUE TITLE
grc possibly breaks zsh completion

### ISSUE THREAD

**Issue by dimitrissch** [garabik/grc#93]
```
grc:v1.11.3
zsh:5.5.1-1
OS:Arch linux
```

I have a rather strange issue.Commands aliased with grc are not completed by zsh when i have 
`setopt NO_COMPLETE_ALIASES` set, but aliases set by me work normal.
For instance 
`alias pacrem='sudo pacman -Rns'` 
is getting pacman completions, while 
`grc --colour=auto /usr/bin/blkid ` is broken.
If i set `setopt COMPLETE_ALIASES` the inverse happens and all my normal aliases stop working while i get completions from grc ones.
Any ideas on how to fix that?

**Comment by xPMo** [comment]
Check out [this PR I wrote](https://github.com/garabik/grc/pull/84), which is a proper completion function for grc.

**Comment by dimitrissch** [comment]
Seems to work fine in my system.Thanks!!
